# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mptiki/dev/CS3100-03

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mptiki/dev/CS3100-03

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mptiki/dev/CS3100-03/CMakeFiles /home/mptiki/dev/CS3100-03/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mptiki/dev/CS3100-03/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Assign3

# Build rule for target.
Assign3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Assign3
.PHONY : Assign3

# fast build rule for target.
Assign3/fast:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/build
.PHONY : Assign3/fast

src/Assign3.o: src/Assign3.cpp.o
.PHONY : src/Assign3.o

# target to build an object file
src/Assign3.cpp.o:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3.cpp.o
.PHONY : src/Assign3.cpp.o

src/Assign3.i: src/Assign3.cpp.i
.PHONY : src/Assign3.i

# target to preprocess a source file
src/Assign3.cpp.i:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3.cpp.i
.PHONY : src/Assign3.cpp.i

src/Assign3.s: src/Assign3.cpp.s
.PHONY : src/Assign3.s

# target to generate assembly for a file
src/Assign3.cpp.s:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3.cpp.s
.PHONY : src/Assign3.cpp.s

src/Assign3Fib.o: src/Assign3Fib.cpp.o
.PHONY : src/Assign3Fib.o

# target to build an object file
src/Assign3Fib.cpp.o:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3Fib.cpp.o
.PHONY : src/Assign3Fib.cpp.o

src/Assign3Fib.i: src/Assign3Fib.cpp.i
.PHONY : src/Assign3Fib.i

# target to preprocess a source file
src/Assign3Fib.cpp.i:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3Fib.cpp.i
.PHONY : src/Assign3Fib.cpp.i

src/Assign3Fib.s: src/Assign3Fib.cpp.s
.PHONY : src/Assign3Fib.s

# target to generate assembly for a file
src/Assign3Fib.cpp.s:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3Fib.cpp.s
.PHONY : src/Assign3Fib.cpp.s

src/Assign3e.o: src/Assign3e.cpp.o
.PHONY : src/Assign3e.o

# target to build an object file
src/Assign3e.cpp.o:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3e.cpp.o
.PHONY : src/Assign3e.cpp.o

src/Assign3e.i: src/Assign3e.cpp.i
.PHONY : src/Assign3e.i

# target to preprocess a source file
src/Assign3e.cpp.i:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3e.cpp.i
.PHONY : src/Assign3e.cpp.i

src/Assign3e.s: src/Assign3e.cpp.s
.PHONY : src/Assign3e.s

# target to generate assembly for a file
src/Assign3e.cpp.s:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3e.cpp.s
.PHONY : src/Assign3e.cpp.s

src/Assign3pi.o: src/Assign3pi.cpp.o
.PHONY : src/Assign3pi.o

# target to build an object file
src/Assign3pi.cpp.o:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3pi.cpp.o
.PHONY : src/Assign3pi.cpp.o

src/Assign3pi.i: src/Assign3pi.cpp.i
.PHONY : src/Assign3pi.i

# target to preprocess a source file
src/Assign3pi.cpp.i:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3pi.cpp.i
.PHONY : src/Assign3pi.cpp.i

src/Assign3pi.s: src/Assign3pi.cpp.s
.PHONY : src/Assign3pi.s

# target to generate assembly for a file
src/Assign3pi.cpp.s:
	$(MAKE) -f CMakeFiles/Assign3.dir/build.make CMakeFiles/Assign3.dir/src/Assign3pi.cpp.s
.PHONY : src/Assign3pi.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Assign3"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Assign3.o"
	@echo "... src/Assign3.i"
	@echo "... src/Assign3.s"
	@echo "... src/Assign3Fib.o"
	@echo "... src/Assign3Fib.i"
	@echo "... src/Assign3Fib.s"
	@echo "... src/Assign3e.o"
	@echo "... src/Assign3e.i"
	@echo "... src/Assign3e.s"
	@echo "... src/Assign3pi.o"
	@echo "... src/Assign3pi.i"
	@echo "... src/Assign3pi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

